### ISSUE TITLE
Multiple Meters

### ISSUE THREAD

**Issue by mquade** [Hofei90/smartmeter#15]
How would be the best way to use multiple meters? 
I have connected them via one RS485 Bus. Addresses are set accordingly. The only solution to find (including start scripts) is to copy everything to a new directory and treat every instance as a complete separate program. In grafana it should then be possible to combine the data sets. 
I would like to have different .toml-Files where I specify the addresses and select the data to capture (the second one only needs to capture I_1, I_2, I_3 - everything else doesn't bother me on that device).
Do you know an easy way to achieve this?

**Comment by Hofei90** [comment]
Hello,
no, unfortunately, there is currently no other option than to create the program separately for each electricity meter.
Maybe I will extend the project so that it supports multiple electricity meters. So far, I have been prevented from doing so by the fact that I only have one electricity meter and can therefore not test the code directly myself.
